server:
  port: 8083
spring:
  application:
    name: resource-server-b
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/spring/protocol/openid-connect/certs
  output:
    ansi:
      enabled: always