server:
  port: 8082
spring:
  application:
    name: resource-server-a
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/spring/protocol/openid-connect/certs
  output:
    ansi:
      enabled: always
custom:
  next-resource-server-url: http://resource-server-b:8083