services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --hostname-strict=false
      - --import-realm
    ports:
       - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - d:/tmp/spring-realm.json:/opt/keycloak/data/import/spring-realm.json
    networks:
      - net
    restart: always
  gateway:
    container_name: gateway
    build:
      context: ..
      dockerfile: docker-config/Gateway.Dockerfile
    depends_on:
      - keycloak
    ports:
      - "8081:8081"
    networks:
      - net
    restart: unless-stopped
  resource-server-a:
    container_name: resource-server-a
    build:
      context: ..
      dockerfile: docker-config/Resource-Server-A.Dockerfile
    depends_on:
      - keycloak
      - gateway
    ports:
      - "8082:8082"
    networks:
      - net
    restart: unless-stopped
  resource-server-b:
    container_name: resource-server-b
    build:
      context: ..
      dockerfile: docker-config/Resource-Server-B.Dockerfile
    depends_on:
      - keycloak
      - gateway
      - resource-server-a
    ports:
      - "8083:8083"
    networks:
      - net
    restart: unless-stopped
networks:
  net:
    driver: bridge